version: 2
jobs:
  build:
    
    working_directory: ~/Factions

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: Factions-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: Factions-{{ checksum "pom.xml" }}
      
      - run: mvn clean package

      - store_artifacts:
          path: target/Factions.jar